### PR TITLE
fix: club cards fade in

### LINKED ISSUE #1211: Bug: Club cards fade in
### Description

Currently, the cuts are looking very sharp We might need to add some hazy effect so that it looks like they are fading in gradually rather than total separable cuts- this can be done with CSS.

Checkout the fade in a style that I have attached in one of the screenshot.

### Proposed Solution

Different styles can be implemented for a `fade away` effect.

### Screenshots

image

image

### Browser 🥦

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no).

### PR DESCRIPTION
**Pull request by r0ld3x**
fix: club cards fade in

closes #1211

### 👷🏻 Changes made  

Added a left and right box shdow with border raduis so that it can look more sylish. Although little work is needed on this pr itself

### 📸 Screenshots 
 
image

### CODE REVIEW

**Comment by r0ld3x** [comment]
> Instead of the fading in effect looking dark can we make it whitish so that it matches with the theme of the website ? That'd be great I guess.
> 
> image
> 

Ok I'll do

**Comment by r0ld3x** [comment]
@tamalCodes check again. :)

**Comment by r0ld3x** [comment]
White is not working msybe because of the white background itself

**Comment by r0ld3x** [comment]
@tamalCodes

**Comment by tamalCodes** [comment]
I see, 

Have you seen our Navbar ? We have a blurry background to it, instead of plain white. In this case can we use something similar to it ?

**Comment by r0ld3x** [comment]
> I see, 
> 
> Have you seen our Navbar ? We have a blurry background to it, instead of plain white. In this case can we use something similar to it ?

So should I add a blurry background behind that?

**Comment by r0ld3x** [comment]
image This with red border or


image with box shadow

or this red borer with little greyish background
image

**Comment by tamalCodes** [comment]
I think it'll be better if we leave it at white.

**Comment by r0ld3x** [comment]
> I think it'll be better if we leave it at white.

wdym? 

ok so just add border-radius

**Pull request closed without merging**
